### ISSUE TITLE
Private by default

### ISSUE THREAD

**Issue by icambron** [qoobaa/s3#100]
That S3 uploads default to public isn't good. You should default to saving things privately and let the user make it public if they wish. If the user means for something to be public but doesn't know to do that, they'll soon find out. If they mean to keep it private but don't know to do that, they'll expose potentially sensitive data to the whole internet.

Would you accept a PR that changes that?

**Comment by exadeci** [comment]
+1

Name | Description
------------ | -------------
x-amz-acl	|The canned ACL to apply to the object. For more information, go to Canned ACL in the Amazon Simple <br>Type: StringValid <br>Values: private \| public-read \|public-read-write \| authenticated-read \| bucket-owner-read \| bucket-owner-full-control<br>Default: **private**

**Comment by qoobaa** [comment]
Could you create a PR for that?

**Comment by icambron** [comment]
Totally can, just wanted to make sure it's a functionality change you'd accept first.

**Comment by qoobaa** [comment]
Sure, we can change it I think.

**Comment by icambron** [comment]
This was fixed by #106, so closing.
