### ISSUE TITLE
require "s3" on production.

### ISSUE THREAD

**Issue by sunil-netsol** [qoobaa/s3#105]
Hi,
I am using gem 's3' in my project to delete the image from the AWS buicket.
I have written code like this.Its working fine in development mode.
     require "s3"
    @university = University.find(params[:id])     
    @service = S3::Service.new(:access_key_id => CONFIG['provider_key'],
                       :secret_access_key => CONFIG['provider_secret'])

But when i pushed this code to production showing me error.

LoadError: can not load such file "--s3"

Even its working fine with the rails c and irb.

Please let me know the solutions.

Thanks
Sunil

**Comment by GusGA** [comment]
Check that the gem s3 is in production group
