### ISSUE TITLE
Error with buckets method

### ISSUE THREAD

**Issue by agrass** [qoobaa/s3#110]
I'm with the last release (0.3.23) and some times the method "buckets" fails after a high timeout with this errors:  "Hostname not known: s3.amazonaws.com", "The specified key does not exist S3::Error::NoSuchKey)" and "S3::Error::ResponseError (S3::Error::ResponseError)" .   Anybody know why would be the reason of this errors?

Thanks!

**Comment by qoobaa** [comment]
I'm not using the gem atm, can anyone confirm it?

**Comment by denodster** [comment]
you might try using a  begin/rescue block to determine what the actual error is.
```
begin
  s.buckets  
rescue Exception => e  
  e.response.inspect  
end
```

I'm actually having a similar problem right now, and the error for me is 
`Net::HTTPForbidden 403 Forbidden readbody=true`
