### ISSUE TITLE
support for ceph-radosgw

### ISSUE THREAD

**Issue by thomasalrin** [qoobaa/s3#111]
This s3 gem is working cool for ceph-radosgw, if i change the ipaddress of host in https://github.com/qoobaa/s3/blob/master/lib/s3.rb file. 
It will be useful for ceph-gateway users, if they can change the host address in runtime.

**Comment by neckhair** [comment]
:+1:

**Comment by seanhandley** [comment]
👍 

Please merge - it means I won't have to override the constant.

**Comment by harrykas** [comment]
Kindly waiting for this feature in release.

**Comment by qoobaa** [comment]
Merged, thanks.
