### ISSUE TITLE
None private acl by default

### ISSUE THREAD

**Issue by maccman** [qoobaa/s3#113]
The Readme states that "Please note that new objects are created with “private” ACL by default."

As far as I can see, that's not true? By default objects have a Everyone => Read ACL.

**Comment by qoobaa** [comment]
I think it's `private` by default: https://github.com/qoobaa/s3/blob/master/lib/s3/object.rb#L159

**Comment by maccman** [comment]
Hmm, I definitely had to set `.acl = :private` to get it private

**Comment by qoobaa** [comment]
I've just released the latest code, could you check it again please?

**Comment by rishijain** [comment]
@qoobaa  I have checked with the latest version and by default it uploads as private. I think it would be a good idea to put this into documentation on how to set the `acl` of any new object. I have it in here https://github.com/qoobaa/s3/pull/114
