### ISSUE TITLE
Support for Secure URL?

### ISSUE THREAD

**Issue by ryanckulp** [qoobaa/s3#117]
The default `.url` is cool, but can I request a secure URL? Otherwise I'm just gsub'ing http => https and that feels silly.

**Comment by qoobaa** [comment]
Seems like a good idea. Could you prepare a PR for that?

**Comment by EBKH** [comment]
You just have to use 'use_ssl:0' to use 'https://' instead of 'http://'

**Comment by ryanckulp** [comment]
thanks @EBKH , and sorry @qoobaa i missed this!
