### ISSUE TITLE
Support for S3 API's outside of AWS

### ISSUE THREAD

**Issue by Karamorf** [qoobaa/s3#118]
My company runs an internal Object Storage with a compatible S3 API. It would be nice if I could specify the host. It works by overwriting the HOST value like this:
S3::HOST = 'some.other.domain.com'

But that does output a warning message:
warning: previous definition of HOST was here

Anywise, more of a nice to have then anything else.

**Comment by adrianmo** [comment]
I'm also interested in using it with a non-AWS S3-compatible API. A part from the host, which can be changed with the workaround @Karamorf mentioned, it would be good to allow custom port configuration, not just 80 or 443.

**Comment by qoobaa** [comment]
From now on, there's a class variable `S3.host` you can change. Changing connection settings like using SSL is possible when you create an `S3::Connection` object.
