### ISSUE TITLE
Version 0.3.26 requires S3::Object#content(true) to fetch object contents

### ISSUE THREAD

**Issue by lisa** [qoobaa/s3#125]
It appears that fc4d193 introduced [a change](https://github.com/qoobaa/s3/blob/v0.3.26/lib/s3/object.rb#L222) that has initialized `@content` in `S3::Object#initialize`. By doing this `if defined?(@content)` [returns true](https://github.com/qoobaa/s3/blob/v0.3.26/lib/s3/object.rb#L87), thus returning a `nil` object.

I made a short test to isolate and verify the issue. Small test and output over various Ruby versions can be located in [a gist](https://gist.github.com/lisa/d6679511c7882b3e6a16dcdc5f694a03).

Unfortunately I'm not sure what the intent is behind fc4d193 so I'm not really able to submit a PR for this.

**Comment by qoobaa** [comment]
I think the main intent was reducing amount of warning messages in Ruby 2.4. Thank you for describing the issue accurately. I'm pretty sure we could replace the `defined?` with `@content ||= ` and it should work fine as well. Are you able to submit a proper PR to fix it?

**Comment by lisa** [comment]
@qoobaa Hi, I opened #126 which should address this.
