### ISSUE TITLE
NameError: uninitialized constant S3::Service::Proxy

### ISSUE THREAD

**Issue by philister** [qoobaa/s3#67]
Hi.

As I ran into this 
https://github.com/qoobaa/s3/issues/34 
I tried to use s3 via gem. Added s3 to my Gemfile, require 's3' and now I get
NameError: uninitialized constant S3::Service::Proxy
when trying to use it.

Do I have to require something more manually?

Thanks and regards, Phil

using rails (2.3.11), s3 (0.3.11), proxies (0.2.1)

**Comment by qoobaa** [comment]
It's probably due to some Rails/ActiveSupport weirdness. Closing it for now.
