### ISSUE TITLE
Saving object as private

### ISSUE THREAD

**Issue by jvkumar** [qoobaa/s3#88]
@qoobaa 
I am trying to save object as private acl. I was looking at https://github.com/qoobaa/s3/blob/master/lib/s3/object.rb#L94 and it seems it alwasy saves as public? Please correct me if I am wrong. So I have monkeypatched s3 object `save` method as: 

```
module S3
  class Object
    def content reload = false
      return @content if @content and not reload
      get_object
      @content
    end

    # Saves the object, returns true if successfull.
     def save is_private = false
      @acl = 'private' if is_private
      put_object
      true
    end
  end
end
```

and then call `myObject.save(true)` . Please let me know if there is already a way to save object as private, then I won't need this hack. Else can you add it?

**Comment by timwaters** [comment]
```
new_object = bucket.objects.build("bender.png"")
new_object.acl = :private
new_object.save
```

for the lazy :smile:
