### ISSUE TITLE
Support for arbitrary headers when creating an object

### ISSUE THREAD

**Issue by rafBM** [qoobaa/s3#89]
For instance `x-amz-server-side-encryption: AES256`. Currently this isn’t possible, right? I could work on this.

**Comment by arthurnn** [comment]
:+1: @rafBM send the PR, and I will review it.

**Comment by rafBM** [comment]
Hey @arthurnn, I don’t plan on working on this anymore. I switched to the official `aws-sdk` version 2. It’s very feature complete and as lightweight as the `s3` gem for it lets you require only the needed modules.
