### ISSUE TITLE
undefined method `to_hash' for nil:NilClass

### ISSUE THREAD

**Issue by Dagnan** [qoobaa/s3#91]
Hi.

When I do a simple object.build(my_key) and object.retrieve I get:

```
undefined method `to_hash' for nil:NilClass
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/s3-0.3.21/lib/s3/object.rb:249:in `parse_headers'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/s3-0.3.21/lib/s3/object.rb:190:in `object_headers'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/s3-0.3.21/lib/s3/object.rb:61:in `retrieve'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/s3-0.3.21/lib/s3/objects_extension.rb:12:in `find_first'
```

Seems simple but not sure if it's a bug or me using the gem wrong.

**Comment by Mehonoshin** [comment]
Hi guys, I faced the same issue.
Created a new bucket via CyberDuck app, the file is present in the bucket. When I try to fetch it with s3 gem, it returns this error.

**Comment by arthurnn** [comment]
This should be fixed in master, please try again, and let me know if it doesnt work.
thanks

**Comment by chav02** [comment]
Getting the exact same error.

created a bucket, added a single file.

    bucket.objects.first.content  => actual file content
    bucket.objects.first.key => actual file key
    bucket.objects.first.request_acl => {"my s3 user"=>"FULL_CONTROL", "Everyone"=>"READ"}
    bucket.objects.first.retrieve => NoMethodError: undefined method `to_hash' for nil:NilClass

precisely according to Dagnan's stacktrace above.  The object_request for headers returns nil. (I guess, boiling down to the Connection.request method, and possibly an empty response from s3)

**Comment by chav02** [comment]
It's indeed fixed in master. It'd be nice to see this change propagated to rubygems.

**Comment by arthurnn** [comment]
@qoobaa can you add me to rubygems so I can cut a new gem. thanks

**Comment by qoobaa** [comment]
@arthurnn done.

**Comment by arthurnn** [comment]
new version released https://rubygems.org/gems/s3/versions/0.3.22

**Comment by RdNetwork** [comment]
I am facing the same problem.

I have a working S3 bucket with files, and the bucket.objects manages to correctly list files, and get their contents, but is unable to retrieve them.

Example of output from the Rails console:
`2.3.0 :009 > bucket`
` => #<S3::Bucket:kyouko> `
`2.3.0 :010 > bucket.objects[125]`
` => #<S3::Object:/kyouko/anime/147799.jpg>` 
`2.3.0 :011 > bucket.objects[125].retrieve`
`NoMethodError: undefined method `to_hash' for nil:NilClass`
`Did you mean?  to_h`
`        from /home/rd/.rvm/gems/ruby-2.3.0/gems/s3-0.3.24/lib/s3/object.rb:245:in `parse_headers'`
`        from /home/rd/.rvm/gems/ruby-2.3.0/gems/s3-0.3.24/lib/s3/object.rb:190:in `object_headers'`
`        from /home/rd/.rvm/gems/ruby-2.3.0/gems/s3-0.3.24/lib/s3/object.rb:61:in `retrieve'`

I am using v0.3.24. I thought this was fixed? Or is it another problem?

**Comment by cavebring** [comment]
+1 on this issue
